# dockerfile.dev

# Imagen base de Node.js para desarrollo
FROM node:20-alpine

# Instalamos pnpm
RUN npm install -g pnpm

# Establecemos el directorio de trabajo
WORKDIR /app

# Copiamos los archivos necesarios para instalar dependencias
COPY package.json tsconfig.json ./

# Instalamos todas las dependencias para desarrollo
RUN pnpm install

# Copiamos el resto de los archivos del proyecto
COPY . .

# Exponemos el puerto 3000
EXPOSE 3000

# Ejecutamos la aplicación en modo desarrollo, con reinicios automáticos
CMD ["pnpm", "run", "dev"]
# CMD ["pnpm", "run", "dev", "--turbo"]
