# Utilizamos una imagen más ligera de Node.js basada en Alpine
FROM node:22-alpine

# Establecemos el directorio de trabajo
WORKDIR /app

# Copiamos solo los archivos necesarios para instalar dependencias primero
COPY package*.json tsconfig.json ./

# Instalamos las dependencias de desarrollo
RUN npm install

# Copiamos el resto de los archivos del proyecto
COPY . .

# Exponemos el puerto 3000
EXPOSE 3000

# Ejecutamos el entorno de desarrollo
CMD ["npm", "run", "dev"]
