# Usa una imagen base de OpenJDK 17
FROM openjdk:17-jdk-slim

# Instala Maven
RUN apt-get update && \
    apt-get install -y maven && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Establece el directorio de trabajo
WORKDIR /app

# Copia solo el archivo pom.xml para que Docker pueda cachear dependencias
COPY pom.xml .

# Descarga las dependencias de Maven (esto solo ocurrirá si pom.xml cambia)
RUN mvn dependency:go-offline

# Copia el código fuente al contenedor
COPY src ./src

# Expone el puerto que utiliza tu aplicación
EXPOSE 8080

# Comando para ejecutar la aplicación
CMD ["mvn", "spring-boot:run"]
