# Utilizando OpenJDK 17 slim
FROM openjdk:17-jdk-slim

# Instalamos Maven en una sola capa para optimización
RUN apt-get update && apt-get install -y --no-install-recommends maven && rm -rf /var/lib/apt/lists/*

# Establecemos el directorio de trabajo
WORKDIR /app

# Copiamos solo los archivos de configuración primero (para aprovechar la cache)
COPY ./pom.xml ./mvnw ./
COPY ./.mvn ./.mvn

# Descargamos las dependencias para cache
RUN ./mvnw dependency:go-offline

# Copiamos el resto de los archivos del proyecto
COPY . .

# Construimos el proyecto sin ejecutar tests
RUN ./mvnw clean install -DskipTests

# Exponemos el puerto 8080
EXPOSE 8080

# Ejecutamos la aplicación en modo desarrollo
ENTRYPOINT ["./mvnw", "spring-boot:run"]
